package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbAlumniservice generated by MyEclipse Persistence Tools
 */

public class TbAlumniservice implements java.io.Serializable {

	// Fields

	private Long alumniserviceId;
	private TbAlumniSt tbAlumni;
	private Long typeFid;
	private String content;
	private String reply;
	private String stateCid;
	private String isDelete;
	private String isNew;
	private Date appTime;
	private Long updateUser;
	private Date updateTime;
	private String memo;
	private Long isRepeat;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	// Constructors

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbAlumniservice() {
	}

	// Property accessors

	public Long getAlumniserviceId() {
		return this.alumniserviceId;
	}

	public void setAlumniserviceId(Long alumniserviceId) {
		this.alumniserviceId = alumniserviceId;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public Long getTypeFid() {
		return this.typeFid;
	}

	public void setTypeFid(Long typeFid) {
		this.typeFid = typeFid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public String getStateCid() {
		return this.stateCid;
	}

	public void setStateCid(String stateCid) {
		this.stateCid = stateCid;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getIsNew() {
		return isNew;
	}

	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}

	public Date getAppTime() {
		return this.appTime;
	}

	public void setAppTime(Date appTime) {
		this.appTime = appTime;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}