package com.laungee.proj.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.laungee.proj.common.biz.ICommonBiz;
import com.laungee.proj.common.util.SpringUtil;

/**
 * TbAlumni generated by MyEclipse Persistence Tools
 */

public class TbAlumniSt implements java.io.Serializable {

	// Fields
	private Long alumniId;
	private String userLogin;
	private String userCard;
	private Long openFid;
	private TbField tbOpen;
	private String sexCid;
	private String nameCn;
	private Long confidenceFid;
	private String mailFirst;
	private String telephoneFirst;
	private String handsetFirst;
	private String studyYear;
	private String studyacademy;
	private String studydepartment;
	private String studyMajor;
	private String studyClass;
	private Long updateUser;
	private Date updateTime;
	private String selfBase;
	private Long alumniLevel;
	private String alumniOrgan;
	private Long isRepeat;
	private Long cardType;		//证件类型
	private String cardsNum;	//证件号码
	private String selfFamily;	//校友家属
	private Set tbVisitAlumnis = new HashSet(0);
	private Set tbTelephoneAlumnis = new HashSet(0);
	private Set tbActionAlumnis = new HashSet(0);
	private Set tbDonations = new HashSet(0);
	private Set tbEmailApps = new HashSet(0);
	private Set tbSeeks = new HashSet(0);
	private Set tbRelations = new HashSet(0);
	private Set tbAlumniservices = new HashSet(0);
	private Set tbCommunityApps = new HashSet(0);
	private Set tbCommunitycreateapplications = new HashSet(0);
	private Set tbUnAlumniSts = new HashSet(0);
	private List alumniCards=new ArrayList();
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}
	
	public List getAlumniCards() {
		if(alumniId!=null&&!"".equals(alumniId)){
			ICommonBiz biz=(ICommonBiz)SpringUtil.getBean("commonBiz");
			try {
				alumniCards=biz.findHQL("from TbAlumniCard a where a.alumniId="+alumniId);
			} catch (Exception e) {
			}
		}
		return alumniCards;
	}
	// Constructors
	public Long getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/** default constructor */
	public TbAlumniSt() {
	}

	public Long getAlumniId() {
		return alumniId;
	}

	public void setAlumniId(Long alumniId) {
		this.alumniId = alumniId;
	}

	public String getNameCn() {
		return nameCn;
	}

	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}
	public Set getTbVisitAlumnis() {
		return tbVisitAlumnis;
	}

	public void setTbVisitAlumnis(Set tbVisitAlumnis) {
		this.tbVisitAlumnis = tbVisitAlumnis;
	}

	public Set getTbTelephoneAlumnis() {
		return tbTelephoneAlumnis;
	}

	public void setTbTelephoneAlumnis(Set tbTelephoneAlumnis) {
		this.tbTelephoneAlumnis = tbTelephoneAlumnis;
	}

	public Set getTbActionAlumnis() {
		return tbActionAlumnis;
	}

	public void setTbActionAlumnis(Set tbActionAlumnis) {
		this.tbActionAlumnis = tbActionAlumnis;
	}

	public Long getConfidenceFid() {
		return confidenceFid;
	}

	public void setConfidenceFid(Long confidenceFid) {
		this.confidenceFid = confidenceFid;
	}

	public String getMailFirst() {
		return mailFirst;
	}

	public void setMailFirst(String mailFirst) {
		this.mailFirst = mailFirst;
	}

	public String getTelephoneFirst() {
		return telephoneFirst;
	}

	public void setTelephoneFirst(String telephoneFirst) {
		this.telephoneFirst = telephoneFirst;
	}

	public String getHandsetFirst() {
		return handsetFirst;
	}

	public void setHandsetFirst(String handsetFirst) {
		this.handsetFirst = handsetFirst;
	}

	public String getStudyYear() {
		return studyYear;
	}

	public void setStudyYear(String studyYear) {
		this.studyYear = studyYear;
	}

	public String getStudyMajor() {
		return studyMajor;
	}

	public void setStudyMajor(String studyMajor) {
		this.studyMajor = studyMajor;
	}

	public String getStudyClass() {
		return studyClass;
	}

	public void setStudyClass(String studyClass) {
		this.studyClass = studyClass;
	}

	public String getSexCid() {
		return sexCid;
	}

	public void setSexCid(String sexCid) {
		this.sexCid = sexCid;
	}

	public Long getOpenFid() {
		return openFid;
	}

	public void setOpenFid(Long openFid) {
		this.openFid = openFid;
	}

	public Set getTbDonations() {
		return tbDonations;
	}

	public void setTbDonations(Set tbDonations) {
		this.tbDonations = tbDonations;
	}

	public Set getTbEmailApps() {
		return tbEmailApps;
	}

	public void setTbEmailApps(Set tbEmailApps) {
		this.tbEmailApps = tbEmailApps;
	}

	public Set getTbSeeks() {
		return tbSeeks;
	}

	public void setTbSeeks(Set tbSeeks) {
		this.tbSeeks = tbSeeks;
	}

	public String getStudydepartment() {
		return studydepartment;
	}

	public void setStudydepartment(String studydepartment) {
		this.studydepartment = studydepartment;
	}

	public String getStudyacademy() {
		return studyacademy;
	}

	public void setStudyacademy(String studyacademy) {
		this.studyacademy = studyacademy;
	}

	public String getUserLogin() {
		return userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public String getUserCard() {
		return userCard;
	}

	public void setUserCard(String userCard) {
		this.userCard = userCard;
	}

	public Set getTbRelations() {
		return tbRelations;
	}

	public void setTbRelations(Set tbRelations) {
		this.tbRelations = tbRelations;
	}

	public TbField getTbOpen() {
		return tbOpen;
	}

	public void setTbOpen(TbField tbOpen) {
		this.tbOpen = tbOpen;
	}

	public Set getTbAlumniservices() {
		return tbAlumniservices;
	}

	public void setTbAlumniservices(Set tbAlumniservices) {
		this.tbAlumniservices = tbAlumniservices;
	}

	public Set getTbCommunityApps() {
		return tbCommunityApps;
	}

	public void setTbCommunityApps(Set tbCommunityApps) {
		this.tbCommunityApps = tbCommunityApps;
	}

	public Set getTbCommunitycreateapplications() {
		return tbCommunitycreateapplications;
	}

	public void setTbCommunitycreateapplications(Set tbCommunitycreateapplications) {
		this.tbCommunitycreateapplications = tbCommunitycreateapplications;
	}

	public Set getTbUnAlumniSts() {
		return tbUnAlumniSts;
	}

	public void setTbUnAlumniSts(Set tbUnAlumniSts) {
		this.tbUnAlumniSts = tbUnAlumniSts;
	}

	public String getSelfBase() {
		return selfBase;
	}

	public void setSelfBase(String selfBase) {
		this.selfBase = selfBase;
	}

	public Long getAlumniLevel() {
		return alumniLevel;
	}

	public void setAlumniLevel(Long alumniLevel) {
		this.alumniLevel = alumniLevel;
	}

	public String getAlumniOrgan() {
		return alumniOrgan;
	}

	public void setAlumniOrgan(String alumniOrgan) {
		this.alumniOrgan = alumniOrgan;
	}

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}
	public Long getCardType() {
		return cardType;
	}
	public void setCardType(Long cardType) {
		this.cardType = cardType;
	}
	public String getCardsNum() {
		return cardsNum;
	}
	public void setCardsNum(String cardsNum) {
		this.cardsNum = cardsNum;
	}
	public String getSelfFamily() {
		return selfFamily;
	}
	public void setSelfFamily(String selfFamily) {
		this.selfFamily = selfFamily;
	}
    



	
}