package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbDonation generated by MyEclipse Persistence Tools
 */

public class TbDonation implements java.io.Serializable {

	// Fields

	private Long donationId;
	private TbAlumniSt tbAlumni;
	private Long typeFid;
	private String donationUser;
	private String donationBenefit;
	private Date donationDate;
	private String donationAddress;
	private String fundNum;
	private Date fundDate;
	private String isFund;
	private String memo;
	private Long updateUser;
	private Date updateTime;
	private String donationCount;
	private String cashWay;
	private TbProgram tbProgram;
	private Long isOpen;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}
	/** default constructor */
	public TbDonation() {
	}

	/** minimal constructor */
	public TbDonation(Long donationId) {
		this.donationId = donationId;
	}

	

	// Property accessors

	public Long getDonationId() {
		return this.donationId;
	}

	public void setDonationId(Long donationId) {
		this.donationId = donationId;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tb) {
		this.tbAlumni = tb;
	}

	public Long getTypeFid() {
		return this.typeFid;
	}

	public void setTypeFid(Long typeFid) {
		this.typeFid = typeFid;
	}

	public String getDonationUser() {
		return this.donationUser;
	}

	public void setDonationUser(String donationUser) {
		this.donationUser = donationUser;
	}

	public String getDonationBenefit() {
		return this.donationBenefit;
	}

	public void setDonationBenefit(String donationBenefit) {
		this.donationBenefit = donationBenefit;
	}

	public Date getDonationDate() {
		return this.donationDate;
	}

	public void setDonationDate(Date donationDate) {
		this.donationDate = donationDate;
	}

	public String getDonationAddress() {
		return this.donationAddress;
	}

	public void setDonationAddress(String donationAddress) {
		this.donationAddress = donationAddress;
	}

	

	public String getFundNum() {
		return this.fundNum;
	}

	public void setFundNum(String fundNum) {
		this.fundNum = fundNum;
	}

	public Date getFundDate() {
		return this.fundDate;
	}

	public void setFundDate(Date fundDate) {
		this.fundDate = fundDate;
	}

	public String getIsFund() {
		return this.isFund;
	}

	public void setIsFund(String isFund) {
		this.isFund = isFund;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	

	public String getDonationCount() {
		return donationCount;
	}

	public void setDonationCount(String donationCount) {
		this.donationCount = donationCount;
	}

	public String getCashWay() {
		return cashWay;
	}

	public void setCashWay(String cashWay) {
		this.cashWay = cashWay;
	}

	public TbProgram getTbProgram() {
		return tbProgram;
	}

	public void setTbProgram(TbProgram tbProgram) {
		this.tbProgram = tbProgram;
	}

	public Long getIsOpen() {
		return isOpen;
	}

	public void setIsOpen(Long isOpen) {
		this.isOpen = isOpen;
	}
	
}