package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbMailHistory generated by MyEclipse Persistence Tools
 */

public class TbMailHistory implements java.io.Serializable {

	// Fields

	private Long historyId;
	private TbMailForm tbMailForm;
	private TbAlumniSt tbAlumni;
	private Long updateUser;
	private Date updateTime;
	private Date sendMail;
	private String memo;
	private TbMailGroup tbMailGroup;
	private Long isRepeat;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}
	// Constructors

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbMailHistory() {
	}

	/** minimal constructor */
	public TbMailHistory(Long historyId) {
		this.historyId = historyId;
	}

	/** full constructor */
	public TbMailHistory(Long historyId, TbMailForm tbMailForm,
			TbAlumniSt tbAlumni, Long updateUser, Date updateTime) {
		this.historyId = historyId;
		this.tbMailForm = tbMailForm;
		this.tbAlumni = tbAlumni;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
	}

	// Property accessors

	public Long getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(Long historyId) {
		this.historyId = historyId;
	}

	public TbMailForm getTbMailForm() {
		return this.tbMailForm;
	}

	public void setTbMailForm(TbMailForm tbMailForm) {
		this.tbMailForm = tbMailForm;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getSendMail() {
		return sendMail;
	}

	public void setSendMail(Date sendMail) {
		this.sendMail = sendMail;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public TbMailGroup getTbMailGroup() {
		return tbMailGroup;
	}

	public void setTbMailGroup(TbMailGroup tbMailGroup) {
		this.tbMailGroup = tbMailGroup;
	}
     
}