package com.laungee.proj.common.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMessage generated by MyEclipse Persistence Tools
 */

public class TbMessage implements java.io.Serializable {

	// Fields

	private Long messgageId;
	private TbCommunity tbCommunity;
	private Long typeFid;
	private String subject;
	private String content;
	private Long numScan;
	private Long numReply;
	private Long createUser;
	private Date createTime;
	private Long updateUser;
	private Date updateTime;
	private String createName;
	private Set tbReplies = new HashSet(0);
	private String imageUrl;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}
	// Constructors

	/** default constructor */
	public TbMessage() {
	}

	/** minimal constructor */
	public TbMessage(Long messgageId) {
		this.messgageId = messgageId;
	}

	/** full constructor */
	public TbMessage(Long messgageId, TbCommunity tbCommunity, Long typeFid,
			String subject, String content, Long numScan, Long numReply,
			Long createUser, Date createTime, Long updateUser, Date updateTime,
			Set tbReplies) {
		this.messgageId = messgageId;
		this.tbCommunity = tbCommunity;
		this.typeFid = typeFid;
		this.subject = subject;
		this.content = content;
		this.numScan = numScan;
		this.numReply = numReply;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.tbReplies = tbReplies;
	}

	// Property accessors

	public Long getMessgageId() {
		return this.messgageId;
	}

	public void setMessgageId(Long messgageId) {
		this.messgageId = messgageId;
	}

	public TbCommunity getTbCommunity() {
		return this.tbCommunity;
	}

	public void setTbCommunity(TbCommunity tbCommunity) {
		this.tbCommunity = tbCommunity;
	}

	public Long getTypeFid() {
		return this.typeFid;
	}

	public void setTypeFid(Long typeFid) {
		this.typeFid = typeFid;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Long getNumScan() {
		return this.numScan;
	}

	public void setNumScan(Long numScan) {
		this.numScan = numScan;
	}

	public Long getNumReply() {
		return this.numReply;
	}

	public void setNumReply(Long numReply) {
		this.numReply = numReply;
	}

	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getTbReplies() {
		return this.tbReplies;
	}

	public void setTbReplies(Set tbReplies) {
		this.tbReplies = tbReplies;
	}

	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
     
}