package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbVisitAlumni generated by MyEclipse Persistence Tools
 */

public class TbVisitAlumni implements java.io.Serializable {

	// Fields

	private Long relId;
	private TbAlumniSt tbAlumni;
	private TbVisit tbVisit;
	private String roleCid;
	private Long updateUser;
	private Date updateTime;
	private Long isRepeat;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	// Constructors

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbVisitAlumni() {
	}

	/** minimal constructor */
	public TbVisitAlumni(Long relId) {
		this.relId = relId;
	}

	
	// Property accessors

	public Long getRelId() {
		return this.relId;
	}

	public void setRelId(Long relId) {
		this.relId = relId;
	}

	

	public TbAlumniSt getTbAlumni() {
		return tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public TbVisit getTbVisit() {
		return this.tbVisit;
	}

	public void setTbVisit(TbVisit tbVisit) {
		this.tbVisit = tbVisit;
	}

	public String getRoleCid() {
		return this.roleCid;
	}

	public void setRoleCid(String roleCid) {
		this.roleCid = roleCid;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}