package com.laungee.proj.common.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbVisit generated by MyEclipse Persistence Tools
 */

public class TbVisit implements java.io.Serializable {

	// Fields

	private Long visitId;
	private String subject;
	private Date visitDate;
	private String department;
	private String memo;
	private String ptrName;
	private Long updateUser;
	private Date updateTime;
	private Long jdrFid;
	private Long visitType;
	private Set tbVisitAlumnis = new HashSet(0);
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	// Constructors

	/** default constructor */
	public TbVisit() {
	}

	/** minimal constructor */
	public TbVisit(Long visitId) {
		this.visitId = visitId;
	}

	/** full constructor */
	public TbVisit(Long visitId, String subject, Date visitDate,
			String department, String memo, Long updateUser, Date updateTime,
			Set tbVisitAlumnis) {
		this.visitId = visitId;
		this.subject = subject;
		this.visitDate = visitDate;
		this.department = department;
		this.memo = memo;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.tbVisitAlumnis = tbVisitAlumnis;
	}

	// Property accessors

	public Long getVisitId() {
		return this.visitId;
	}

	public void setVisitId(Long visitId) {
		this.visitId = visitId;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Date getVisitDate() {
		return this.visitDate;
	}

	public void setVisitDate(Date visitDate) {
		this.visitDate = visitDate;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getTbVisitAlumnis() {
		return this.tbVisitAlumnis;
	}

	public void setTbVisitAlumnis(Set tbVisitAlumnis) {
		this.tbVisitAlumnis = tbVisitAlumnis;
	}

	public String getPtrName() {
		return ptrName;
	}

	public void setPtrName(String ptrName) {
		this.ptrName = ptrName;
	}

	public Long getJdrFid() {
		return jdrFid;
	}

	public void setJdrFid(Long jdrFid) {
		this.jdrFid = jdrFid;
	}

	public Long getVisitType() {
		return visitType;
	}

	public void setVisitType(Long visitType) {
		this.visitType = visitType;
	}
    
  
	
   
}