package com.laungee.proj.common.model;

/**
 * VwMailgroupalumni generated by MyEclipse Persistence Tools
 */

public class VwMailgroupalumni implements java.io.Serializable {

	// Fields

	private Long relId;
	private Long groupId;
	private Long alumniId;
	private String nameCn;
	private String relationName;
	private String address;
	private String postcode;
	private String groupName;

	// Constructors

	/** default constructor */
	public VwMailgroupalumni() {
	}

	/** minimal constructor */
	public VwMailgroupalumni(Long relId) {
		this.relId = relId;
	}

	/** full constructor */
	public VwMailgroupalumni(Long relId, Long groupId, String nameCn,
			String relationName, String address, String postcode) {
		this.relId = relId;
		this.groupId = groupId;
		this.nameCn = nameCn;
		this.relationName = relationName;
		this.address = address;
		this.postcode = postcode;
	}

	// Property accessors

	public Long getRelId() {
		return this.relId;
	}

	public void setRelId(Long relId) {
		this.relId = relId;
	}

	public Long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	public String getNameCn() {
		return this.nameCn;
	}

	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}

	public String getRelationName() {
		return this.relationName;
	}

	public void setRelationName(String relationName) {
		this.relationName = relationName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Long getAlumniId() {
		return alumniId;
	}

	public void setAlumniId(Long alumniId) {
		this.alumniId = alumniId;
	}

    
}