package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbCommunitycreateapplication generated by MyEclipse Persistence Tools
 */

public class TbCommunitycreateapplication implements java.io.Serializable {

	// Fields

	private Long communitycreateapplicationid;
	private TbAlumniSt tbAlumni;
	private String alumniid;
	private Long typeFid;
	private String communitycreateapplicationsubj;
	private String communitycreateapplicationcont;
	private Date communitycreateapplicationdate;
	private String communitycreateapplicationstat;
	private String communitycreateapplicationrepl;
	private String memo;
	private String isNew;
	private String isDelete;
	private Long updateUser;
	private Date updateTime;
	private Long isRepeat;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}
	// Constructors

	/** default constructor */
	public TbCommunitycreateapplication() {
	}

	// Property accessors

	public Long getCommunitycreateapplicationid() {
		return this.communitycreateapplicationid;
	}

	public void setCommunitycreateapplicationid(
			Long communitycreateapplicationid) {
		this.communitycreateapplicationid = communitycreateapplicationid;
	}

	public TbAlumniSt getTbAlumni() {
		return tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public String getAlumniid() {
		return this.alumniid;
	}

	public void setAlumniid(String alumniid) {
		this.alumniid = alumniid;
	}

	public Long getTypeFid() {
		return this.typeFid;
	}

	public void setTypeFid(Long typeFid) {
		this.typeFid = typeFid;
	}

	public String getCommunitycreateapplicationsubj() {
		return this.communitycreateapplicationsubj;
	}

	public void setCommunitycreateapplicationsubj(
			String communitycreateapplicationsubj) {
		this.communitycreateapplicationsubj = communitycreateapplicationsubj;
	}

	public String getCommunitycreateapplicationcont() {
		return this.communitycreateapplicationcont;
	}

	public void setCommunitycreateapplicationcont(
			String communitycreateapplicationcont) {
		this.communitycreateapplicationcont = communitycreateapplicationcont;
	}

	public Date getCommunitycreateapplicationdate() {
		return this.communitycreateapplicationdate;
	}

	public void setCommunitycreateapplicationdate(
			Date communitycreateapplicationdate) {
		this.communitycreateapplicationdate = communitycreateapplicationdate;
	}

	public String getCommunitycreateapplicationstat() {
		return this.communitycreateapplicationstat;
	}

	public void setCommunitycreateapplicationstat(
			String communitycreateapplicationstat) {
		this.communitycreateapplicationstat = communitycreateapplicationstat;
	}

	public String getCommunitycreateapplicationrepl() {
		return this.communitycreateapplicationrepl;
	}

	public void setCommunitycreateapplicationrepl(
			String communitycreateapplicationrepl) {
		this.communitycreateapplicationrepl = communitycreateapplicationrepl;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getIsNew() {
		return isNew;
	}

	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public Long getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

}