package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbEmailAlumni generated by MyEclipse Persistence Tools
 */

public class TbEmailAlumni implements java.io.Serializable {

	// Fields

	private Long relId;
	private TbAlumniSt tbAlumni;
	private TbEmailGroup tbEmailGroup;
	private Long updateUser;
	private Date updateTime;
	private Long isRepeat;

	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbEmailAlumni() {
	}

	/** minimal constructor */
	public TbEmailAlumni(Long relId) {
		this.relId = relId;
	}

	/** full constructor */
	public TbEmailAlumni(Long relId, TbAlumniSt tbAlumni,
			TbEmailGroup tbEmailGroup, Long updateUser, Date updateTime) {
		this.relId = relId;
		this.tbAlumni = tbAlumni;
		this.tbEmailGroup = tbEmailGroup;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
	}

	// Property accessors

	public Long getRelId() {
		return this.relId;
	}

	public void setRelId(Long relId) {
		this.relId = relId;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public TbEmailGroup getTbEmailGroup() {
		return this.tbEmailGroup;
	}

	public void setTbEmailGroup(TbEmailGroup tbEmailGroup) {
		this.tbEmailGroup = tbEmailGroup;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}