package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbEvent generated by MyEclipse Persistence Tools
 */

public class TbEvent implements java.io.Serializable {

	// Fields

	private Long eventId;
	private TbCommunity tbCommunity;
	private String subject;
	private String content;
	private Long createUser;
	private Date createDate;
	private Long updateUser;
	private Date updateTime;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	// Constructors

	/** default constructor */
	public TbEvent() {
	}

	/** minimal constructor */
	public TbEvent(Long eventId) {
		this.eventId = eventId;
	}

	/** full constructor */
	public TbEvent(Long eventId, TbCommunity tbCommunity, String subject,
			String content, Long createUser, Date createDate, Long updateUser,
			Date updateTime) {
		this.eventId = eventId;
		this.tbCommunity = tbCommunity;
		this.subject = subject;
		this.content = content;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
	}

	// Property accessors

	public Long getEventId() {
		return this.eventId;
	}

	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}

	public TbCommunity getTbCommunity() {
		return this.tbCommunity;
	}

	public void setTbCommunity(TbCommunity tbCommunity) {
		this.tbCommunity = tbCommunity;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}