package com.laungee.proj.common.model;

/**
 * TbMailAlumni generated by MyEclipse Persistence Tools
 */

public class TbMailAlumni implements java.io.Serializable {

	// Fields

	private Long relId;
	private TbAlumniSt tbAlumni;
	private TbMailGroup tbMailGroup;
	private Long updateUser;
	private Long updateTime;
	private Long isRepeat;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	// Constructors

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbMailAlumni() {
	}

	/** minimal constructor */
	public TbMailAlumni(Long relId) {
		this.relId = relId;
	}

	/** full constructor */
	public TbMailAlumni(Long relId, TbAlumniSt tbAlumni, TbMailGroup tbMailGroup,
			Long updateUser, Long updateTime) {
		this.relId = relId;
		this.tbAlumni = tbAlumni;
		this.tbMailGroup = tbMailGroup;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
	}

	// Property accessors

	public Long getRelId() {
		return this.relId;
	}

	public void setRelId(Long relId) {
		this.relId = relId;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public TbMailGroup getTbMailGroup() {
		return this.tbMailGroup;
	}

	public void setTbMailGroup(TbMailGroup tbMailGroup) {
		this.tbMailGroup = tbMailGroup;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Long getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

}