package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbMember generated by MyEclipse Persistence Tools
 */

public class TbMember implements java.io.Serializable {

	// Fields

	private Long memberId;
	private TbAcademy tbAcademyByMajorId;
	private Long majorId;
	private TbAcademy tbAcademyByNodeId;
	private Long nodeId;
	private String studentCode;
	private String studentName;
	private Long updateUser;
	private Date updateTime;
	 private String xuezhi;
     private String xueli;
     private String sex;
     private String ssxy;
     private String studentType;
     private String rxqdw;
     private String memo;
     private String nationFid;
     private String countryFid;
     private String degree;
	// Constructors
     //2013-07-16新增入学年，毕业年
     private String yearJoin;
     private String yearOff;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	public String getYearJoin() {
		return yearJoin;
	}

	public void setYearJoin(String yearJoin) {
		this.yearJoin = yearJoin;
	}

	public String getYearOff() {
		return yearOff;
	}

	public void setYearOff(String yearOff) {
		this.yearOff = yearOff;
	}

	public String getCountryFid() {
		return countryFid;
	}

	public void setCountryFid(String countryFid) {
		this.countryFid = countryFid;
	}

	public String getDegree() {
		return degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public Long getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/** default constructor */
	public TbMember() {
	}

	/** minimal constructor */
	public TbMember(Long memberId) {
		this.memberId = memberId;
	}

	/** full constructor */
	public TbMember(Long memberId, TbAcademy tbAcademyByMajorId,
			TbAcademy tbAcademyByNodeId, String studentCode, String studentName) {
		this.memberId = memberId;
		this.tbAcademyByMajorId = tbAcademyByMajorId;
		this.tbAcademyByNodeId = tbAcademyByNodeId;
		this.studentCode = studentCode;
		this.studentName = studentName;
	}

	// Property accessors

	public Long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	public TbAcademy getTbAcademyByMajorId() {
		return this.tbAcademyByMajorId;
	}

	public void setTbAcademyByMajorId(TbAcademy tbAcademyByMajorId) {
		if(tbAcademyByMajorId==null){
			if(majorId!=null){
				this.setMajorId(null);
			}
		}else{
			if(!tbAcademyByMajorId.getNodeId().equals(majorId)){
				this.setMajorId(tbAcademyByMajorId.getNodeId());
			}
		}
		this.tbAcademyByMajorId = tbAcademyByMajorId;
	}

	public TbAcademy getTbAcademyByNodeId() {
		return this.tbAcademyByNodeId;
	}

	public void setTbAcademyByNodeId(TbAcademy tbAcademyByNodeId) {
		if(tbAcademyByNodeId==null){
			if(nodeId!=null){
				this.setNodeId(null);
			}
		}else{
			if(!tbAcademyByNodeId.getNodeId().equals(nodeId)){
				this.setNodeId(tbAcademyByNodeId.getNodeId());
			}
		}
		this.tbAcademyByNodeId = tbAcademyByNodeId;
	}

	public String getStudentCode() {
		return this.studentCode;
	}

	public void setStudentCode(String studentCode) {
		this.studentCode = studentCode;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public String getXuezhi() {
		return xuezhi;
	}

	public void setXuezhi(String xuezhi) {
		this.xuezhi = xuezhi;
	}

	public String getXueli() {
		return xueli;
	}

	public void setXueli(String xueli) {
		this.xueli = xueli;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSsxy() {
		return ssxy;
	}

	public void setSsxy(String ssxy) {
		this.ssxy = ssxy;
	}

	public String getStudentType() {
		return studentType;
	}

	public void setStudentType(String studentType) {
		this.studentType = studentType;
	}

	public String getRxqdw() {
		return rxqdw;
	}

	public void setRxqdw(String rxqdw) {
		this.rxqdw = rxqdw;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getNationFid() {
		return nationFid;
	}

	public void setNationFid(String nationFid) {
		this.nationFid = nationFid;
	}

	public Long getMajorId() {
		return majorId;
	}

	public void setMajorId(Long majorId) {
		this.majorId = majorId;
	}

	public Long getNodeId() {
		return nodeId;
	}

	public void setNodeId(Long nodeId) {
		this.nodeId = nodeId;
	}
    
}