package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbSeek generated by MyEclipse Persistence Tools
 */

public class TbSeek implements java.io.Serializable {

	// Fields

	private Long seekId;
	private TbAlumniSt tbAlumni;
	private String subject;
	private String content;
	private Date appDate;
	private String stateCid;
	private String isDelete;
	private String isNew;
	private String reply;
	private String memo;
	private Long updateUser;
	private Date updateTime;
	private Long isRepeat;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	// Constructors

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbSeek() {
	}

	// Property accessors

	public Long getSeekId() {
		return this.seekId;
	}

	public void setSeekId(Long seekId) {
		this.seekId = seekId;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	public String getStateCid() {
		return this.stateCid;
	}

	public void setStateCid(String stateCid) {
		this.stateCid = stateCid;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getIsNew() {
		return isNew;
	}

	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}

	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}