package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbEmaillHistory generated by MyEclipse Persistence Tools
 */

public class TbEmaillHistory implements java.io.Serializable {

	// Fields

	private Long historyId;
	private TbEmailForm2 tbEmailForm2;
	private TbAlumniSt tbAlumni;
	private Long updateUser;
	private Date updateTime;
	private Date sendDate;
	private String memo;
	private TbEmailGroup tbEmailGroup;
	private Long isRepeat;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}
	// Constructors

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbEmaillHistory() {
	}

	/** minimal constructor */
	public TbEmaillHistory(Long historyId) {
		this.historyId = historyId;
	}

	/** full constructor */
	public TbEmaillHistory(Long historyId, TbEmailForm2 tbEmailForm2,
			TbAlumniSt tbAlumni, Long updateUser, Date updateTime) {
		this.historyId = historyId;
		this.tbEmailForm2 = tbEmailForm2;
		this.tbAlumni = tbAlumni;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
	}

	// Property accessors

	public Long getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(Long historyId) {
		this.historyId = historyId;
	}

	public TbEmailForm2 getTbEmailForm2() {
		return this.tbEmailForm2;
	}

	public void setTbEmailForm2(TbEmailForm2 tbEmailForm2) {
		this.tbEmailForm2 = tbEmailForm2;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getSendDate() {
		return sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public TbEmailGroup getTbEmailGroup() {
		return tbEmailGroup;
	}

	public void setTbEmailGroup(TbEmailGroup tbEmailGroup) {
		this.tbEmailGroup = tbEmailGroup;
	}
    
}