package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbEmailApp generated by MyEclipse Persistence Tools
 */

public class TbEmailApp implements java.io.Serializable {

	// Fields

	private Long appId;
	private TbAlumniSt tbAlumni;
	private String stateCid;
	private String reply;
	private String emailFirst;
	private String emailSecond;
	private String emailThird;
	private Date emailapplicationdate;
	private String isDelete;
	private String isNew;
	private String memo;
	private Long updateUser;
	private Date updateTime;
	private Long isRepeat;

	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	public Long getIsRepeat() {
		return isRepeat;
	}

	public void setIsRepeat(Long isRepeat) {
		this.isRepeat = isRepeat;
	}

	/** default constructor */
	public TbEmailApp() {
	}

	// Property accessors

	public Long getAppId() {
		return this.appId;
	}

	public void setAppId(Long appId) {
		this.appId = appId;
	}

	public TbAlumniSt getTbAlumni() {
		return this.tbAlumni;
	}

	public void setTbAlumni(TbAlumniSt tbAlumni) {
		this.tbAlumni = tbAlumni;
	}

	public String getStateCid() {
		return this.stateCid;
	}

	public void setStateCid(String stateCid) {
		this.stateCid = stateCid;
	}

	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public String getEmailFirst() {
		return this.emailFirst;
	}

	public void setEmailFirst(String emailFirst) {
		this.emailFirst = emailFirst;
	}

	public String getEmailSecond() {
		return this.emailSecond;
	}

	public void setEmailSecond(String emailSecond) {
		this.emailSecond = emailSecond;
	}

	public String getEmailThird() {
		return this.emailThird;
	}

	public void setEmailThird(String emailThird) {
		this.emailThird = emailThird;
	}

	public Date getEmailapplicationdate() {
		return this.emailapplicationdate;
	}

	public void setEmailapplicationdate(Date emailapplicationdate) {
		this.emailapplicationdate = emailapplicationdate;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getIsNew() {
		return isNew;
	}

	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}