package com.laungee.proj.common.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbMailForm generated by MyEclipse Persistence Tools
 */

public class TbMailForm implements java.io.Serializable {

	// Fields

	private Long formId;
	private String formName;
	private String subject;
	private String content;
	private String memo;
	private Long updateUser;
	private Date updateTime;
	private Set tbMailHistories = new HashSet(0);
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	// Constructors

	/** default constructor */
	public TbMailForm() {
	}

	/** minimal constructor */
	public TbMailForm(Long formId) {
		this.formId = formId;
	}

	/** full constructor */
	public TbMailForm(Long formId, String formName, String subject,
			String content, String memo, Long updateUser, Date updateTime,
			Set tbMailHistories) {
		this.formId = formId;
		this.formName = formName;
		this.subject = subject;
		this.content = content;
		this.memo = memo;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.tbMailHistories = tbMailHistories;
	}

	// Property accessors

	public Long getFormId() {
		return this.formId;
	}

	public void setFormId(Long formId) {
		this.formId = formId;
	}

	public String getFormName() {
		return this.formName;
	}

	public void setFormName(String formName) {
		this.formName = formName;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Set getTbMailHistories() {
		return this.tbMailHistories;
	}

	public void setTbMailHistories(Set tbMailHistories) {
		this.tbMailHistories = tbMailHistories;
	}

}