package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbReply generated by MyEclipse Persistence Tools
 */

public class TbReply implements java.io.Serializable {

	// Fields

	private Long replyId;
	private TbMessage tbMessage;
	private Long typeFid;
	private String content;
	private String createUser;
	private Date createTime;
	private Long updateUser;
	private Date updateTime;
	private String createName;
	private String imageUrl;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}
	// Constructors

	/** default constructor */
	public TbReply() {
	}

	/** minimal constructor */
	public TbReply(Long replyId) {
		this.replyId = replyId;
	}

	/** full constructor */
	public TbReply(Long replyId, TbMessage tbMessage, Long typeFid,
			String content, String createUser, Date createTime,
			Long updateUser, Date updateTime) {
		this.replyId = replyId;
		this.tbMessage = tbMessage;
		this.typeFid = typeFid;
		this.content = content;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
	}

	// Property accessors

	public Long getReplyId() {
		return this.replyId;
	}

	public void setReplyId(Long replyId) {
		this.replyId = replyId;
	}

	public TbMessage getTbMessage() {
		return this.tbMessage;
	}

	public void setTbMessage(TbMessage tbMessage) {
		this.tbMessage = tbMessage;
	}

	public Long getTypeFid() {
		return this.typeFid;
	}

	public void setTypeFid(Long typeFid) {
		this.typeFid = typeFid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
    
}