package com.laungee.proj.common.model;

import java.util.Date;

/**
 * TbSharestudent generated by MyEclipse Persistence Tools
 */

public class TbSharestudent implements java.io.Serializable {

	// Fields

	private Long shareid;
	private String createTime;
	private String academyName;
	private String departmentName;
	private String majorNamge;
	private String className;
	private String studentCode;
	private String sutdentName;
	private String academicYear;
	private String advancedDegree;
	private Long updateUser;
	private Date updateTime;
	private String academyCode;
	private String departmentCode;
	private String majorCode;
	private String classCode;
	private String memo;
	private String rxqdw;
	private String sex;
    private String xsxy;
	private String studentType;
	private String nationFid;
	//2013-06-04新增，学位，国籍
	private String degree;
	private String country;
	//2013-06-25新增，是否从系统导入标识
	private String isSys;
	//2013-06-28新增
	private String leaveTime;	//离校年
	private String flag="create";		//标记类型、create为入学年，leave为离校年
	// Constructors
    //2013-07-16新增入学年，毕业年
    private String yearJoin;
    private String yearOff;
	private Long creationUser;
	private String creationTime;
	// Constructors

	public Long getCreationUser() {
		return creationUser;
	}

	public void setCreationUser(Long creationUser) {
		this.creationUser = creationUser;
	}

	public String getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(String creationTime) {
		this.creationTime = creationTime;
	}

	public String getYearJoin() {
		return yearJoin;
	}

	public void setYearJoin(String yearJoin) {
		this.yearJoin = yearJoin;
	}

	public String getYearOff() {
		return yearOff;
	}

	public void setYearOff(String yearOff) {
		this.yearOff = yearOff;
	}

	public String getLeaveTime() {
		return leaveTime;
	}

	public void setLeaveTime(String leaveTime) {
		this.leaveTime = leaveTime;
	}

	public String getIsSys() {
		return isSys;
	}

	public void setIsSys(String isSys) {
		this.isSys = isSys;
	}

	public String getDegree() {
		return degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	/** default constructor */
	public TbSharestudent() {
	}

	/** minimal constructor */
	public TbSharestudent(Long shareid) {
		this.shareid = shareid;
	}

	/** full constructor */
	public TbSharestudent(Long shareid, String createTime, String academyName,
			String departmentName, String majorNamge, String className,
			String studentCode, String sutdentName, String academicYear,
			String advancedDegree, Long updateUser, Date updateTime,
			String nodeCode) {
		this.shareid = shareid;
		this.createTime = createTime;
		this.academyName = academyName;
		this.departmentName = departmentName;
		this.majorNamge = majorNamge;
		this.className = className;
		this.studentCode = studentCode;
		this.sutdentName = sutdentName;
		this.academicYear = academicYear;
		this.advancedDegree = advancedDegree;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		
	}

	// Property accessors

	public Long getShareid() {
		return this.shareid;
	}

	public void setShareid(Long shareid) {
		this.shareid = shareid;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getAcademyName() {
		return this.academyName;
	}

	public void setAcademyName(String academyName) {
		this.academyName = academyName;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getMajorNamge() {
		return this.majorNamge;
	}

	public void setMajorNamge(String majorNamge) {
		this.majorNamge = majorNamge;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getStudentCode() {
		return this.studentCode;
	}

	public void setStudentCode(String studentCode) {
		this.studentCode = studentCode;
	}

	public String getSutdentName() {
		return this.sutdentName;
	}

	public void setSutdentName(String sutdentName) {
		this.sutdentName = sutdentName;
	}

	public String getAcademicYear() {
		return this.academicYear;
	}

	public void setAcademicYear(String academicYear) {
		this.academicYear = academicYear;
	}

	public String getAdvancedDegree() {
		return this.advancedDegree;
	}

	public void setAdvancedDegree(String advancedDegree) {
		this.advancedDegree = advancedDegree;
	}

	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getAcademyCode() {
		return academyCode;
	}

	public void setAcademyCode(String academyCode) {
		this.academyCode = academyCode;
	}

	public String getDepartmentCode() {
		return departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	public String getMajorCode() {
		return majorCode;
	}

	public void setMajorCode(String majorCode) {
		this.majorCode = majorCode;
	}

	public String getClassCode() {
		return classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getRxqdw() {
		return rxqdw;
	}

	public void setRxqdw(String rxqdw) {
		this.rxqdw = rxqdw;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getXsxy() {
		return xsxy;
	}

	public void setXsxy(String xsxy) {
		this.xsxy = xsxy;
	}

	public String getStudentType() {
		return studentType;
	}

	public void setStudentType(String studentType) {
		this.studentType = studentType;
	}

	public String getNationFid() {
		return nationFid;
	}

	public void setNationFid(String nationFid) {
		this.nationFid = nationFid;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
   
	

}