package com.laungee.proj.common.model;

import java.util.Date;

/**
 * VwStudentmemberInfo generated by MyEclipse Persistence Tools
 */

public class VwStudentmemberInfo implements java.io.Serializable {

	// Fields
	private Long memberId;
	private Long majorId;
	private Long classId;
	private String nationFid;
	private String studentName;
	private String studentCode;
	private Date updateTime;
	private String className;
	private String majorName;
	private Long departmentId;
	private String departmentName;
	private Long academyId;
	private String academyName;
	private String createTime;
	private String xuezhi;
	private String xueli;
	private String sex;
	private String ssxy;
	private String studentType;
	private String rxqdw;
	private String memo;
	private String organname;
    private String countryFid;
    private String degree;
	//2013-06-28新增
	private String leaveTime;	//离校年
	// Constructors

    //2013-07-16新增入学年，毕业年
    private String yearJoin;
    private String yearOff;

	public String getLeaveTime() {
		return leaveTime;
	}

	public void setLeaveTime(String leaveTime) {
		this.leaveTime = leaveTime;
	}

	public String getCountryFid() {
		return countryFid;
	}

	public void setCountryFid(String countryFid) {
		this.countryFid = countryFid;
	}

	public String getDegree() {
		return degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	/** default constructor */
	public VwStudentmemberInfo() {
	}

	/** minimal constructor */
	public VwStudentmemberInfo(Long memberId) {
		this.memberId = memberId;
	}

	/** full constructor */
	public VwStudentmemberInfo(Long memberId, Long majorId, Long classId,
			String studentName, Date updateTime, String className,
			String majorName, Long departmentId, String departmentName,
			Long academyId, String academyName, String createTime) {
		this.memberId = memberId;
		this.majorId = majorId;
		this.classId = classId;
		this.studentName = studentName;
		this.updateTime = updateTime;
		this.className = className;
		this.majorName = majorName;
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.academyId = academyId;
		this.academyName = academyName;
		this.createTime = createTime;
	}

	// Property accessors

	public Long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	public Long getMajorId() {
		return this.majorId;
	}

	public void setMajorId(Long majorId) {
		this.majorId = majorId;
	}

	public Long getClassId() {
		return this.classId;
	}

	public void setClassId(Long classId) {
		this.classId = classId;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getMajorName() {
		return this.majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	public Long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Long departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public Long getAcademyId() {
		return this.academyId;
	}

	public void setAcademyId(Long academyId) {
		this.academyId = academyId;
	}

	public String getAcademyName() {
		return this.academyName;
	}

	public void setAcademyName(String academyName) {
		this.academyName = academyName;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getStudentCode() {
		return studentCode;
	}

	public void setStudentCode(String studentCode) {
		this.studentCode = studentCode;
	}

	public String getXuezhi() {
		return xuezhi;
	}

	public void setXuezhi(String xuezhi) {
		this.xuezhi = xuezhi;
	}

	public String getXueli() {
		return xueli;
	}

	public void setXueli(String xueli) {
		this.xueli = xueli;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSsxy() {
		return ssxy;
	}

	public void setSsxy(String ssxy) {
		this.ssxy = ssxy;
	}

	public String getStudentType() {
		return studentType;
	}

	public void setStudentType(String studentType) {
		this.studentType = studentType;
	}

	public String getRxqdw() {
		return rxqdw;
	}

	public void setRxqdw(String rxqdw) {
		this.rxqdw = rxqdw;
	}

	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getNationFid() {
		return nationFid;
	}

	public void setNationFid(String nationFid) {
		this.nationFid = nationFid;
	}

	public String getOrganname() {
		return organname;
	}

	public void setOrganname(String organname) {
		this.organname = organname;
	}

	public String getYearJoin() {
		return yearJoin;
	}

	public void setYearJoin(String yearJoin) {
		this.yearJoin = yearJoin;
	}

	public String getYearOff() {
		return yearOff;
	}

	public void setYearOff(String yearOff) {
		this.yearOff = yearOff;
	}
    
	
    

}