<%@ page language="java" pageEncoding="UTF-8"%><%@ include file="../common/include.jsp"%><% String basePath = request.getScheme()+"://"+request.getServerName(); if(("http".equals(request.getScheme().toLowerCase()) && request.getServerPort()==80) || ("https".equals(request.getScheme().toLowerCase()) && request.getServerPort()==443)){ basePath += request.getContextPath()+"/"; }else{ basePath += ":"+request.getServerPort()+request.getContextPath()+"/"; } %>
{
	result:'success',
	id:'<c:out value="${bean.orderId}"/>',
	comm:'<c:out value="${bean.commId}"/>',
	commName:'<c:out value="${bean.commName}"/>',
	commPic:'<c:if test="${not empty bean.commPic}"><%=basePath%><c:out value="${bean.commPic}"/></c:if>',
	option:'<c:out value="${bean.commDetailId}"/>',
	optionName:'<c:out value="${bean.commDetailName}"/>',
	optionCostfee:'<fmt:formatNumber value="${bean.commCostfee}" pattern="0.##" type="number"/>',
	optionSalefee:'<fmt:formatNumber value="${bean.commSalefee}" pattern="0.##" type="number"/>',
	optionCount:'<fmt:formatNumber value="${bean.commNum}" pattern="0" type="number"/>',
	shipType:'<c:out value="${bean.shippingType}"/>',
	shipFee:'<fmt:formatNumber value="${bean.shippingFee}" pattern="0.##" type="number"/>',
	shipCurFee:'<fmt:formatNumber value="${bean.shippingCurfee}" pattern="0.##" type="number"/>',
	donationFee:'<fmt:formatNumber value="${bean.donationFee}" pattern="0.##" type="number"/>',
	orderAmount:'<fmt:formatNumber value="${bean.orderFee}" pattern="0.##" type="number"/>',
	orderNo:'<c:out value="${bean.orderNo}"/>',
	orderSource:'<c:out value="${bean.orderSource}"/>',
	orderType:'<c:out value="${bean.orderType}"/>',
	orderStatus:'<c:out value="${bean.orderStatus}"/>',
	orderTime:'<fmt:formatDate value="${bean.orderTime}" pattern="yyyy-MM-dd HH:mm"/>',
	orderOkTime:'<fmt:formatDate value="${bean.orderOkTime}" pattern="yyyy-MM-dd HH:mm"/>',
	suportIndex:'<c:out value="${bean.suportIndex}"/>',
	personName:'<c:out value="${bean.buyerName}"/>',
	niMing:'<c:out value="${bean.niMing}" default="0"/>',
	personIp:'<c:out value="${bean.buyerIp}"/>',
	personSex:'<c:out value="${bean.buyerSex}"/>',
	personEmail:'<c:out value="${bean.buyerEmail}"/>',
	personPhone:'<c:out value="${bean.buyerMobile}"/>',
	personTel:'<c:out value="${bean.buyerPhone}"/>',
	addressZip:'<c:out value="${bean.buyerZipcode}"/>',
	addressDetail:'<c:if test="${not empty bean.buyerSheng}"><c:out value="${bean.buyerSheng}"/>（省）</c:if><c:if test="${not empty bean.buyerShi}"><c:out value="${bean.buyerShi}"/>（市）</c:if><c:if test="${not empty bean.buyerQu}"><c:out value="${bean.buyerQu}"/>（区）</c:if><c:if test="${not empty bean.buyerAddress}"><c:out value="${bean.buyerAddress}"/></c:if>',
	alumniFlag:'<c:out value="${bean.alumniFlag}"/>',
	alumniUn:'<c:out value="${bean.unAlumniId}"/>',
	studyYearin:'<c:out value="${bean.studyYearin}"/>',
	studyYearover:'<c:out value="${bean.studyYearover}"/>',
	studyAcademy:'<c:out value="${bean.studyAcademy}"/>',
	studyMajor:'<c:out value="${bean.studyMajor}"/>',
	studyClass:'<c:out value="${bean.studyClass}"/>',
	studyNum:'<c:out value="${bean.studyNum}"/>',
	studyDegree:'<c:out value="${bean.studyDegree}"/>',
	workCompany:'<c:out value="${bean.workCompany}"/>',
	workDepart:'<c:out value="${bean.workDepart}"/>',
	workDuty:'<c:out value="${bean.workDuty}"/>',
	orderMemo:'<my:escapeHtml value="${bean.orderMemo}" removeTarget="false" changePath="false"/>',
	receipt:'<my:escapeHtml value="${bean.receipt}" removeTarget="false" changePath="true"/>',
	starNum:'<fmt:formatNumber value="${bean.starNum}" pattern="0" type="number"/>',
	starMemo:'<my:escapeHtml value="${bean.starMemo}" removeTarget="false" changePath="false"/>',
	starTime:'<fmt:formatDate value="${bean.starTime}" pattern="yyyy-MM-dd HH:mm"/>'
}