<%@ page language="java" pageEncoding="UTF-8"%><%@ include file="../common/include.jsp"%><% String basePath = request.getScheme()+"://"+request.getServerName(); if(("http".equals(request.getScheme().toLowerCase()) && request.getServerPort()==80) || ("https".equals(request.getScheme().toLowerCase()) && request.getServerPort()==443)){ basePath += request.getContextPath()+"/"; }else{ basePath += ":"+request.getServerPort()+request.getContextPath()+"/"; } %>
{
	result:'success',
	id:'<c:out value="${bean.orderId}"/>',
	projName:'<c:out value="${bean.projName}"/>',
	projUrl:'<c:out value="${bean.projUrl}"/>',
	orderAmountType:'<c:out value="${bean.orderAmountType}"/>',
	orderAmountView:'<fmt:formatNumber value="${bean.orderAmountView}" pattern="0.##" type="number"/>',
	orderAmountUnit:'<c:out value="${bean.orderAmountUnit}"/>',
	orderAmount:'<fmt:formatNumber value="${bean.orderAmount}" pattern="0.##" type="number"/>',
	orderNo:'<c:out value="${bean.orderNum}"/>',
	orderType:'<c:out value="${bean.orderType}"/>',
	orderStatus:'<c:out value="${bean.orderStatus}"/>',
	orderTime:'<fmt:formatDate value="${bean.orderTime}" pattern="yyyy-MM-dd HH:mm"/>',
	orderOkTime:'<fmt:formatDate value="${bean.orderOkTime}" pattern="yyyy-MM-dd HH:mm"/>',
	suportIndex:'<c:out value="${bean.suportIndex}"/>',
	needZhengshu:'<c:out value="${bean.needZhengshu}"/>',
	needFapiao:'<c:out value="${bean.needFapiao}"/>',
	personType:'<c:out value="${bean.personType}"/>',
	personCount:'<c:out value="${bean.personCount}" default="1"/>',
	personName:'<c:out value="${bean.personName}"/>',
	niMing:'<c:out value="${bean.niMing}" default="0"/>',
	personIp:'<c:out value="${bean.personIp}"/>',
	personSex:'<c:out value="${bean.personSex}"/>',
	personEmail:'<c:out value="${bean.personEmail}"/>',
	personPhone:'<c:out value="${bean.personPhone}"/>',
	personTel:'<c:out value="${bean.personTel}"/>',
	addressZip:'<c:out value="${bean.addressZip}"/>',
	addressDetail:'<c:if test="${not empty bean.addressSheng}"><c:out value="${bean.addressSheng}"/>（省）</c:if><c:if test="${not empty bean.addressShi}"><c:out value="${bean.addressShi}"/>（市）</c:if><c:if test="${not empty bean.addressQu}"><c:out value="${bean.addressQu}"/>（区）</c:if><c:if test="${not empty bean.addressDetail}"><c:out value="${bean.addressDetail}"/></c:if>',
	alumniFlag:'<c:out value="${bean.alumniFlag}"/>',
	alumniUn:'<c:out value="${bean.unAlumniId}"/>',
	studyYearin:'<c:out value="${bean.studyYearin}"/>',
	studyYearover:'<c:out value="${bean.studyYearover}"/>',
	studyAcademy:'<c:out value="${bean.studyAcademy}"/>',
	studyMajor:'<c:out value="${bean.studyMajor}"/>',
	studyClass:'<c:out value="${bean.studyClass}"/>',
	studyNum:'<c:out value="${bean.studyNum}"/>',
	studyDegree:'<c:out value="${bean.studyDegree}"/>',
	workCompany:'<c:out value="${bean.workCompany}"/>',
	workDepart:'<c:out value="${bean.workDepart}"/>',
	workDuty:'<c:out value="${bean.workDuty}"/>',
	orderMemo:'<my:escapeHtml value="${bean.orderMemo}" removeTarget="false" changePath="false"/>',
	receipt:'<my:escapeHtml value="${bean.receipt}" removeTarget="false" changePath="true"/>'
}